<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260121065117 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE genres (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, locale VARCHAR(5) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE record_labels (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, locale VARCHAR(5) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE games DROP CONSTRAINT fk_ff232b31b4d51b7e');
        $this->addSql('ALTER TABLE games DROP CONSTRAINT fk_ff232b31791b7458');
        $this->addSql('ALTER TABLE players DROP CONSTRAINT fk_264e43a667c3651b');
        $this->addSql('DROP TABLE games');
        $this->addSql('DROP TABLE players');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE games (id UUID NOT NULL, board JSON NOT NULL, current_turn VARCHAR(1) NOT NULL, status VARCHAR(20) NOT NULL, winner VARCHAR(10) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_activity_x TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_activity_o TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, visibility VARCHAR(10) NOT NULL, join_code VARCHAR(6) DEFAULT NULL, player_x_id UUID DEFAULT NULL, player_o_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_ff232b31e64d7d01 ON games (join_code)');
        $this->addSql('CREATE INDEX idx_ff232b31b4d51b7e ON games (player_x_id)');
        $this->addSql('CREATE INDEX idx_ff232b31791b7458 ON games (player_o_id)');
        $this->addSql('CREATE TABLE players (id UUID NOT NULL, name VARCHAR(50) NOT NULL, session_id VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, active_game_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_264e43a667c3651b ON players (active_game_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_264e43a65e237e06 ON players (name)');
        $this->addSql('ALTER TABLE games ADD CONSTRAINT fk_ff232b31b4d51b7e FOREIGN KEY (player_x_id) REFERENCES players (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE games ADD CONSTRAINT fk_ff232b31791b7458 FOREIGN KEY (player_o_id) REFERENCES players (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE players ADD CONSTRAINT fk_264e43a667c3651b FOREIGN KEY (active_game_id) REFERENCES games (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE genres');
        $this->addSql('DROP TABLE record_labels');
    }
}
